apiVersion: v1
data:
  dex.config: |-
    connectors:
      # GitLab
      - type: gitlab
        id: gitlab
        name: Our GitLab
        config:
          baseURL: http://gitlab.domain.com
          clientID: <ID>
          clientSecret: <SECRET>
        useLoginAsID: false
  statusbadge.enabled: "true"
  url: https://argocd.domain.com
  users.session.duration: 8h
kind: ConfigMap
metadata:
  name: argocd-cm

