apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
   - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml 
   - ca-root.yaml
   - argocd-server-grpc-ingress.yaml
   - argocd-server-http-ingress.yaml
   - https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
